# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  citizenfilemanagementapi:
    image: citizenfilemanagementapi
    build:
      context: .
      dockerfile: CitizenFileManagement.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5110:5110
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
