# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  citizenfilemanagementapi:
    container_name: Web-Api
    image: citizenfilemanagementapi
    build:
      context: .
      dockerfile: CitizenFileManagement.API/Dockerfile
    ports:
      - 5110:5110
    environment:
      - ASPNETCORE_URLS=http://+:5110
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=CitizenFileDB;User Id=postgres;Password=your_password;
      - Minio__Endpoint=http://minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin123
    # depends_on:
    #   - postgresdb
    #   - minio

  postgresdb:
    container_name: DataBase
    image: postgres:latest
    environment:
      POSTGRES_DB: CitizenFileDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - 5434:5434
    volumes:
      - ./containers/products-db:/var/lib/postgresql/data

  minio:
    container_name: FileStorage
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - 9002:9000
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: